### ISSUE TITLE
Ontologi-filer peker til master branch

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/organization-catalog#118]
Det ser ikke ut til å være et problem pr nå, men hva skjer hvis vi gjør noen endringer?

**Comment by stigbd** [comment]
En ordentlig fiks her ville vere å publisere disse tre ontologi-filene til `data.norge.no/vocabulary/<asdf>`.
Dette krever antagelegvis også endring i uri'er og tilhøyrande ETL-jobbing.

**Comment by NilsOveTen** [comment]
> En ordentlig fiks her ville vere å publisere disse tre ontologi-filene til `data.norge.no/vocabulary/<asdf>`. Dette krever antagelegvis også endring i uri'er og tilhøyrande ETL-jobbing.

Ikke spesielt til ETL-jobbing, men flere tjenseter kommer til å feile så snart disse blir endret uri'ene. De tjenestene jeg kommer på dette kanskje vil påvirke er `fdk-reasoning-service` og `fdk-metadata-quality-service`, `fdk-reports-bff` og `fdk-organization-bff`

Det blir veldig tydelig i staging hva som kreves så snart vi får ut endret org-cat der

**Comment by NilsOveTen** [comment]
Tjenester som må oppdateres etter en flytting:
 - dcat-ap-no-validator-service
 - skos-ap-no-begrep
 - fdk-reasoning-service
 - dcat-ap-no
 - fdk-rdf-parser
 - fdk-reports-bff

**Comment by NilsOveTen** [comment]
Og om vi flytter filene fra organization-catalog så kan vi også flytte `fdk.owl` fra reasoning-service
(https://github.com/Informasjonsforvaltning/fdk-reasoning-service/blob/main/src/main/resources/ontology/fdk.owl)
